### PR TITLE
update CHANGELOG

### PR DESCRIPTION
**Pull request by k-okada**
- please run catkin_prepare_release and git push and git push --tag
- please ask ps4sys maintainer for putting his ps4eys_init.py code into longjie repository

### CODE REVIEW

**Comment by k-okada** [comment]
ping -> @longjie

**Comment by longjie** [comment]
I will do both after coming back home. Sorry for delay.

**Comment by longjie** [comment]
> please run catkin_prepare_release and git push and git push --tag

This is done.

> please ask ps4sys maintainer for putting his ps4eys_init.py code into longjie repository

I sent e-mail to the maintainer to ask that.  Expect good news.

**Comment by k-okada** [comment]
Thank you!!!
released at -> https://github.com/ros/rosdistro/pull/6792

**Comment by k-okada** [comment]
as for indigo, we have to wait for https://github.com/ros-drivers/gscam/issues/17

**Pull request merged**
